/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedProgressionRouteImport } from './routes/_authenticated/progression'
import { Route as AuthenticatedPlusRouteImport } from './routes/_authenticated/plus'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMonProfilRouteImport } from './routes/_authenticated/mon-profil'
import { Route as AuthenticatedFacturationRouteImport } from './routes/_authenticated/facturation'
import { Route as AuthenticatedEmploiDuTempsRouteImport } from './routes/_authenticated/emploi-du-temps'
import { Route as AuthenticatedElevesRouteImport } from './routes/_authenticated/eleves'
import { Route as AuthenticatedEcolesRouteImport } from './routes/_authenticated/ecoles'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedAnneesScolairesRouteImport } from './routes/_authenticated/annees-scolaires'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'
import { Route as AuthenticatedAbsencesRouteImport } from './routes/_authenticated/absences'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedParametresRappelsRouteImport } from './routes/_authenticated/parametres.rappels'
import { Route as AuthenticatedParametresNotificationsRouteImport } from './routes/_authenticated/parametres.notifications'
import { Route as AuthenticatedFacturationIdRouteImport } from './routes/_authenticated/facturation.$id'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin.parametres'
import { Route as AuthenticatedAdminFacturationRouteImport } from './routes/_authenticated/admin.facturation'
import { Route as AuthenticatedAdminAnneesScolairesRouteImport } from './routes/_authenticated/admin.annees-scolaires'
import { Route as AuthenticatedFacturationIdPdfRouteImport } from './routes/_authenticated/facturation.$id.pdf'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressionRoute =
  AuthenticatedProgressionRouteImport.update({
    id: '/progression',
    path: '/progression',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlusRoute = AuthenticatedPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonProfilRoute = AuthenticatedMonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacturationRoute =
  AuthenticatedFacturationRouteImport.update({
    id: '/facturation',
    path: '/facturation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmploiDuTempsRoute =
  AuthenticatedEmploiDuTempsRouteImport.update({
    id: '/emploi-du-temps',
    path: '/emploi-du-temps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElevesRoute = AuthenticatedElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcolesRoute = AuthenticatedEcolesRouteImport.update({
  id: '/ecoles',
  path: '/ecoles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnneesScolairesRoute =
  AuthenticatedAnneesScolairesRouteImport.update({
    id: '/annees-scolaires',
    path: '/annees-scolaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAbsencesRoute = AuthenticatedAbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedParametresRappelsRoute =
  AuthenticatedParametresRappelsRouteImport.update({
    id: '/rappels',
    path: '/rappels',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedParametresNotificationsRoute =
  AuthenticatedParametresNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedParametresRoute,
  } as any)
const AuthenticatedFacturationIdRoute =
  AuthenticatedFacturationIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedFacturationRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFacturationRoute =
  AuthenticatedAdminFacturationRouteImport.update({
    id: '/facturation',
    path: '/facturation',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnneesScolairesRoute =
  AuthenticatedAdminAnneesScolairesRouteImport.update({
    id: '/annees-scolaires',
    path: '/annees-scolaires',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedFacturationIdPdfRoute =
  AuthenticatedFacturationIdPdfRouteImport.update({
    id: '/pdf',
    path: '/pdf',
    getParentRoute: () => AuthenticatedFacturationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/annees-scolaires': typeof AuthenticatedAnneesScolairesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/ecoles': typeof AuthenticatedEcolesRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/facturation': typeof AuthenticatedFacturationRouteWithChildren
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/plus': typeof AuthenticatedPlusRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/annees-scolaires': typeof AuthenticatedAdminAnneesScolairesRoute
  '/admin/facturation': typeof AuthenticatedAdminFacturationRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/facturation/$id': typeof AuthenticatedFacturationIdRouteWithChildren
  '/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/parametres/rappels': typeof AuthenticatedParametresRappelsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/facturation/$id/pdf': typeof AuthenticatedFacturationIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/absences': typeof AuthenticatedAbsencesRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/annees-scolaires': typeof AuthenticatedAnneesScolairesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/ecoles': typeof AuthenticatedEcolesRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/facturation': typeof AuthenticatedFacturationRouteWithChildren
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/plus': typeof AuthenticatedPlusRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/rapports': typeof AuthenticatedRapportsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/admin/annees-scolaires': typeof AuthenticatedAdminAnneesScolairesRoute
  '/admin/facturation': typeof AuthenticatedAdminFacturationRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/facturation/$id': typeof AuthenticatedFacturationIdRouteWithChildren
  '/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/parametres/rappels': typeof AuthenticatedParametresRappelsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/facturation/$id/pdf': typeof AuthenticatedFacturationIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/absences': typeof AuthenticatedAbsencesRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/annees-scolaires': typeof AuthenticatedAnneesScolairesRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/ecoles': typeof AuthenticatedEcolesRoute
  '/_authenticated/eleves': typeof AuthenticatedElevesRoute
  '/_authenticated/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/_authenticated/facturation': typeof AuthenticatedFacturationRouteWithChildren
  '/_authenticated/mon-profil': typeof AuthenticatedMonProfilRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRouteWithChildren
  '/_authenticated/plus': typeof AuthenticatedPlusRoute
  '/_authenticated/progression': typeof AuthenticatedProgressionRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/admin/annees-scolaires': typeof AuthenticatedAdminAnneesScolairesRoute
  '/_authenticated/admin/facturation': typeof AuthenticatedAdminFacturationRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/facturation/$id': typeof AuthenticatedFacturationIdRouteWithChildren
  '/_authenticated/parametres/notifications': typeof AuthenticatedParametresNotificationsRoute
  '/_authenticated/parametres/rappels': typeof AuthenticatedParametresRappelsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/facturation/$id/pdf': typeof AuthenticatedFacturationIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/absences'
    | '/accueil'
    | '/admin'
    | '/annees-scolaires'
    | '/classes'
    | '/ecoles'
    | '/eleves'
    | '/emploi-du-temps'
    | '/facturation'
    | '/mon-profil'
    | '/notes'
    | '/parametres'
    | '/plus'
    | '/progression'
    | '/rapports'
    | '/support'
    | '/admin/annees-scolaires'
    | '/admin/facturation'
    | '/admin/parametres'
    | '/admin/plans'
    | '/admin/utilisateurs'
    | '/facturation/$id'
    | '/parametres/notifications'
    | '/parametres/rappels'
    | '/admin/'
    | '/facturation/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/absences'
    | '/accueil'
    | '/annees-scolaires'
    | '/classes'
    | '/ecoles'
    | '/eleves'
    | '/emploi-du-temps'
    | '/facturation'
    | '/mon-profil'
    | '/notes'
    | '/parametres'
    | '/plus'
    | '/progression'
    | '/rapports'
    | '/support'
    | '/admin/annees-scolaires'
    | '/admin/facturation'
    | '/admin/parametres'
    | '/admin/plans'
    | '/admin/utilisateurs'
    | '/facturation/$id'
    | '/parametres/notifications'
    | '/parametres/rappels'
    | '/admin'
    | '/facturation/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/absences'
    | '/_authenticated/accueil'
    | '/_authenticated/admin'
    | '/_authenticated/annees-scolaires'
    | '/_authenticated/classes'
    | '/_authenticated/ecoles'
    | '/_authenticated/eleves'
    | '/_authenticated/emploi-du-temps'
    | '/_authenticated/facturation'
    | '/_authenticated/mon-profil'
    | '/_authenticated/notes'
    | '/_authenticated/parametres'
    | '/_authenticated/plus'
    | '/_authenticated/progression'
    | '/_authenticated/rapports'
    | '/_authenticated/support'
    | '/_authenticated/admin/annees-scolaires'
    | '/_authenticated/admin/facturation'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/facturation/$id'
    | '/_authenticated/parametres/notifications'
    | '/_authenticated/parametres/rappels'
    | '/_authenticated/admin/'
    | '/_authenticated/facturation/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progression': {
      id: '/_authenticated/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof AuthenticatedProgressionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus': {
      id: '/_authenticated/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof AuthenticatedPlusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-profil': {
      id: '/_authenticated/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof AuthenticatedMonProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facturation': {
      id: '/_authenticated/facturation'
      path: '/facturation'
      fullPath: '/facturation'
      preLoaderRoute: typeof AuthenticatedFacturationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emploi-du-temps': {
      id: '/_authenticated/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof AuthenticatedEmploiDuTempsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eleves': {
      id: '/_authenticated/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AuthenticatedElevesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecoles': {
      id: '/_authenticated/ecoles'
      path: '/ecoles'
      fullPath: '/ecoles'
      preLoaderRoute: typeof AuthenticatedEcolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/annees-scolaires': {
      id: '/_authenticated/annees-scolaires'
      path: '/annees-scolaires'
      fullPath: '/annees-scolaires'
      preLoaderRoute: typeof AuthenticatedAnneesScolairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/absences': {
      id: '/_authenticated/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AuthenticatedAbsencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/parametres/rappels': {
      id: '/_authenticated/parametres/rappels'
      path: '/rappels'
      fullPath: '/parametres/rappels'
      preLoaderRoute: typeof AuthenticatedParametresRappelsRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/parametres/notifications': {
      id: '/_authenticated/parametres/notifications'
      path: '/notifications'
      fullPath: '/parametres/notifications'
      preLoaderRoute: typeof AuthenticatedParametresNotificationsRouteImport
      parentRoute: typeof AuthenticatedParametresRoute
    }
    '/_authenticated/facturation/$id': {
      id: '/_authenticated/facturation/$id'
      path: '/$id'
      fullPath: '/facturation/$id'
      preLoaderRoute: typeof AuthenticatedFacturationIdRouteImport
      parentRoute: typeof AuthenticatedFacturationRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/facturation': {
      id: '/_authenticated/admin/facturation'
      path: '/facturation'
      fullPath: '/admin/facturation'
      preLoaderRoute: typeof AuthenticatedAdminFacturationRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/annees-scolaires': {
      id: '/_authenticated/admin/annees-scolaires'
      path: '/annees-scolaires'
      fullPath: '/admin/annees-scolaires'
      preLoaderRoute: typeof AuthenticatedAdminAnneesScolairesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/facturation/$id/pdf': {
      id: '/_authenticated/facturation/$id/pdf'
      path: '/pdf'
      fullPath: '/facturation/$id/pdf'
      preLoaderRoute: typeof AuthenticatedFacturationIdPdfRouteImport
      parentRoute: typeof AuthenticatedFacturationIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnneesScolairesRoute: typeof AuthenticatedAdminAnneesScolairesRoute
  AuthenticatedAdminFacturationRoute: typeof AuthenticatedAdminFacturationRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnneesScolairesRoute:
    AuthenticatedAdminAnneesScolairesRoute,
  AuthenticatedAdminFacturationRoute: AuthenticatedAdminFacturationRoute,
  AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedFacturationIdRouteChildren {
  AuthenticatedFacturationIdPdfRoute: typeof AuthenticatedFacturationIdPdfRoute
}

const AuthenticatedFacturationIdRouteChildren: AuthenticatedFacturationIdRouteChildren =
  {
    AuthenticatedFacturationIdPdfRoute: AuthenticatedFacturationIdPdfRoute,
  }

const AuthenticatedFacturationIdRouteWithChildren =
  AuthenticatedFacturationIdRoute._addFileChildren(
    AuthenticatedFacturationIdRouteChildren,
  )

interface AuthenticatedFacturationRouteChildren {
  AuthenticatedFacturationIdRoute: typeof AuthenticatedFacturationIdRouteWithChildren
}

const AuthenticatedFacturationRouteChildren: AuthenticatedFacturationRouteChildren =
  {
    AuthenticatedFacturationIdRoute:
      AuthenticatedFacturationIdRouteWithChildren,
  }

const AuthenticatedFacturationRouteWithChildren =
  AuthenticatedFacturationRoute._addFileChildren(
    AuthenticatedFacturationRouteChildren,
  )

interface AuthenticatedParametresRouteChildren {
  AuthenticatedParametresNotificationsRoute: typeof AuthenticatedParametresNotificationsRoute
  AuthenticatedParametresRappelsRoute: typeof AuthenticatedParametresRappelsRoute
}

const AuthenticatedParametresRouteChildren: AuthenticatedParametresRouteChildren =
  {
    AuthenticatedParametresNotificationsRoute:
      AuthenticatedParametresNotificationsRoute,
    AuthenticatedParametresRappelsRoute: AuthenticatedParametresRappelsRoute,
  }

const AuthenticatedParametresRouteWithChildren =
  AuthenticatedParametresRoute._addFileChildren(
    AuthenticatedParametresRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAbsencesRoute: typeof AuthenticatedAbsencesRoute
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnneesScolairesRoute: typeof AuthenticatedAnneesScolairesRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedEcolesRoute: typeof AuthenticatedEcolesRoute
  AuthenticatedElevesRoute: typeof AuthenticatedElevesRoute
  AuthenticatedEmploiDuTempsRoute: typeof AuthenticatedEmploiDuTempsRoute
  AuthenticatedFacturationRoute: typeof AuthenticatedFacturationRouteWithChildren
  AuthenticatedMonProfilRoute: typeof AuthenticatedMonProfilRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRouteWithChildren
  AuthenticatedPlusRoute: typeof AuthenticatedPlusRoute
  AuthenticatedProgressionRoute: typeof AuthenticatedProgressionRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAbsencesRoute: AuthenticatedAbsencesRoute,
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnneesScolairesRoute: AuthenticatedAnneesScolairesRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedEcolesRoute: AuthenticatedEcolesRoute,
  AuthenticatedElevesRoute: AuthenticatedElevesRoute,
  AuthenticatedEmploiDuTempsRoute: AuthenticatedEmploiDuTempsRoute,
  AuthenticatedFacturationRoute: AuthenticatedFacturationRouteWithChildren,
  AuthenticatedMonProfilRoute: AuthenticatedMonProfilRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRouteWithChildren,
  AuthenticatedPlusRoute: AuthenticatedPlusRoute,
  AuthenticatedProgressionRoute: AuthenticatedProgressionRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
