/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRapportsRouteImport } from './routes/_authenticated/rapports'
import { Route as AuthenticatedProgressionRouteImport } from './routes/_authenticated/progression'
import { Route as AuthenticatedPlusRouteImport } from './routes/_authenticated/plus'
import { Route as AuthenticatedParametresRouteImport } from './routes/_authenticated/parametres'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMonProfilRouteImport } from './routes/_authenticated/mon-profil'
import { Route as AuthenticatedEmploiDuTempsRouteImport } from './routes/_authenticated/emploi-du-temps'
import { Route as AuthenticatedElevesRouteImport } from './routes/_authenticated/eleves'
import { Route as AuthenticatedEcolesRouteImport } from './routes/_authenticated/ecoles'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedAnneesScolairesRouteImport } from './routes/_authenticated/annees-scolaires'
import { Route as AuthenticatedAccueilRouteImport } from './routes/_authenticated/accueil'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRapportsRoute = AuthenticatedRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgressionRoute =
  AuthenticatedProgressionRouteImport.update({
    id: '/progression',
    path: '/progression',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlusRoute = AuthenticatedPlusRouteImport.update({
  id: '/plus',
  path: '/plus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParametresRoute = AuthenticatedParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonProfilRoute = AuthenticatedMonProfilRouteImport.update({
  id: '/mon-profil',
  path: '/mon-profil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmploiDuTempsRoute =
  AuthenticatedEmploiDuTempsRouteImport.update({
    id: '/emploi-du-temps',
    path: '/emploi-du-temps',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedElevesRoute = AuthenticatedElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEcolesRoute = AuthenticatedEcolesRouteImport.update({
  id: '/ecoles',
  path: '/ecoles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnneesScolairesRoute =
  AuthenticatedAnneesScolairesRouteImport.update({
    id: '/annees-scolaires',
    path: '/annees-scolaires',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccueilRoute = AuthenticatedAccueilRouteImport.update({
  id: '/accueil',
  path: '/accueil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/annees-scolaires': typeof AuthenticatedAnneesScolairesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/ecoles': typeof AuthenticatedEcolesRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plus': typeof AuthenticatedPlusRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/rapports': typeof AuthenticatedRapportsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accueil': typeof AuthenticatedAccueilRoute
  '/annees-scolaires': typeof AuthenticatedAnneesScolairesRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/ecoles': typeof AuthenticatedEcolesRoute
  '/eleves': typeof AuthenticatedElevesRoute
  '/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/mon-profil': typeof AuthenticatedMonProfilRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/parametres': typeof AuthenticatedParametresRoute
  '/plus': typeof AuthenticatedPlusRoute
  '/progression': typeof AuthenticatedProgressionRoute
  '/rapports': typeof AuthenticatedRapportsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accueil': typeof AuthenticatedAccueilRoute
  '/_authenticated/annees-scolaires': typeof AuthenticatedAnneesScolairesRoute
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/ecoles': typeof AuthenticatedEcolesRoute
  '/_authenticated/eleves': typeof AuthenticatedElevesRoute
  '/_authenticated/emploi-du-temps': typeof AuthenticatedEmploiDuTempsRoute
  '/_authenticated/mon-profil': typeof AuthenticatedMonProfilRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/parametres': typeof AuthenticatedParametresRoute
  '/_authenticated/plus': typeof AuthenticatedPlusRoute
  '/_authenticated/progression': typeof AuthenticatedProgressionRoute
  '/_authenticated/rapports': typeof AuthenticatedRapportsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accueil'
    | '/annees-scolaires'
    | '/classes'
    | '/ecoles'
    | '/eleves'
    | '/emploi-du-temps'
    | '/mon-profil'
    | '/notes'
    | '/parametres'
    | '/plus'
    | '/progression'
    | '/rapports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accueil'
    | '/annees-scolaires'
    | '/classes'
    | '/ecoles'
    | '/eleves'
    | '/emploi-du-temps'
    | '/mon-profil'
    | '/notes'
    | '/parametres'
    | '/plus'
    | '/progression'
    | '/rapports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accueil'
    | '/_authenticated/annees-scolaires'
    | '/_authenticated/classes'
    | '/_authenticated/ecoles'
    | '/_authenticated/eleves'
    | '/_authenticated/emploi-du-temps'
    | '/_authenticated/mon-profil'
    | '/_authenticated/notes'
    | '/_authenticated/parametres'
    | '/_authenticated/plus'
    | '/_authenticated/progression'
    | '/_authenticated/rapports'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rapports': {
      id: '/_authenticated/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof AuthenticatedRapportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/progression': {
      id: '/_authenticated/progression'
      path: '/progression'
      fullPath: '/progression'
      preLoaderRoute: typeof AuthenticatedProgressionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plus': {
      id: '/_authenticated/plus'
      path: '/plus'
      fullPath: '/plus'
      preLoaderRoute: typeof AuthenticatedPlusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parametres': {
      id: '/_authenticated/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AuthenticatedParametresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-profil': {
      id: '/_authenticated/mon-profil'
      path: '/mon-profil'
      fullPath: '/mon-profil'
      preLoaderRoute: typeof AuthenticatedMonProfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/emploi-du-temps': {
      id: '/_authenticated/emploi-du-temps'
      path: '/emploi-du-temps'
      fullPath: '/emploi-du-temps'
      preLoaderRoute: typeof AuthenticatedEmploiDuTempsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eleves': {
      id: '/_authenticated/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof AuthenticatedElevesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ecoles': {
      id: '/_authenticated/ecoles'
      path: '/ecoles'
      fullPath: '/ecoles'
      preLoaderRoute: typeof AuthenticatedEcolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/annees-scolaires': {
      id: '/_authenticated/annees-scolaires'
      path: '/annees-scolaires'
      fullPath: '/annees-scolaires'
      preLoaderRoute: typeof AuthenticatedAnneesScolairesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accueil': {
      id: '/_authenticated/accueil'
      path: '/accueil'
      fullPath: '/accueil'
      preLoaderRoute: typeof AuthenticatedAccueilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccueilRoute: typeof AuthenticatedAccueilRoute
  AuthenticatedAnneesScolairesRoute: typeof AuthenticatedAnneesScolairesRoute
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedEcolesRoute: typeof AuthenticatedEcolesRoute
  AuthenticatedElevesRoute: typeof AuthenticatedElevesRoute
  AuthenticatedEmploiDuTempsRoute: typeof AuthenticatedEmploiDuTempsRoute
  AuthenticatedMonProfilRoute: typeof AuthenticatedMonProfilRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedParametresRoute: typeof AuthenticatedParametresRoute
  AuthenticatedPlusRoute: typeof AuthenticatedPlusRoute
  AuthenticatedProgressionRoute: typeof AuthenticatedProgressionRoute
  AuthenticatedRapportsRoute: typeof AuthenticatedRapportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccueilRoute: AuthenticatedAccueilRoute,
  AuthenticatedAnneesScolairesRoute: AuthenticatedAnneesScolairesRoute,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedEcolesRoute: AuthenticatedEcolesRoute,
  AuthenticatedElevesRoute: AuthenticatedElevesRoute,
  AuthenticatedEmploiDuTempsRoute: AuthenticatedEmploiDuTempsRoute,
  AuthenticatedMonProfilRoute: AuthenticatedMonProfilRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedParametresRoute: AuthenticatedParametresRoute,
  AuthenticatedPlusRoute: AuthenticatedPlusRoute,
  AuthenticatedProgressionRoute: AuthenticatedProgressionRoute,
  AuthenticatedRapportsRoute: AuthenticatedRapportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
